image: python:3.8

stages:
  - preprocess
  - analyze
  - report

preprocess-data:
  stage: preprocess
  script:
    - echo "Preprocessing data..."
    - mkdir -p data/processed  # Create the directory if it doesn't exist
    - pip install -r requirements.txt
    - python scripts/preprocess.py
  artifacts:
    paths:
      - data/processed/processed_data.csv

analyze-data:
  stage: analyze
  script:
    - echo "Analyzing data..."
    - mkdir -p data/analysis  # Create the directory if it doesn't exist
    - pip install -r requirements.txt  # Ensure requirements are installed
    - python scripts/analyze.py
  dependencies:
    - preprocess-data
  artifacts:
    paths:
      - data/analysis/analysis_results.csv

generate-report:
  stage: report
  script:
    - echo "Generating report..."
    - mkdir -p data/reports  # Create the directory if it doesn't exist
    - pip install -r requirements.txt  # Ensure requirements are installed
    - python scripts/generate_report.py
  dependencies:
    - analyze-data
  artifacts:
    paths:
      - data/reports/report.pdf
